backend:
  name: git-gateway
  repo: adamdjbrett/davidbrett.im
  branch: master 
media_folder: 'assets/'
collections:
  - name: "indexs"
    label: "Home Page"
    extension: "md"
    editor:
      preview: true
    files:
     - file: "index.md"
       label: "Home Page Area"
       name: "index"
       widget: "object"
       fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Feature Text', name: 'feature_text', widget: 'string' }
          - { label: 'Feature Image', name: 'feature_image', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "abo"
    label: "About Page"
    extension: "md"
    editor:
      preview: true
    files:
     - file: "about.md"
       label: "About Page Area"
       name: "about"
       widget: "object"
       fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "ct"
    label: "Contact Page"
    extension: "md"
    editor:
      preview: true
    files:
     - file: "contact.md"
       label: "Contact Page Area"
       name: "contact"
       widget: "object"
       fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'posts'
    label: 'Blog Posting'
    folder: '_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    editor:
      preview: true
    fields:
    - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
    - { label: 'Feature Image', name: 'feature_image', widget: 'image' }
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Description', name: 'description', widget: 'string' }
    - { label: 'Categories', name: 'categories', widget: 'string' }
    - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "configs"
    label: "Configuration"
    extension: "yml"
    editor:
      preview: false
    files:
     - file: "_config.yml"
       label: "Config Site"
       name: "conf"
       widget: list
       fields:
         - { name: 'title', label: 'Title', widget: 'string' }
         - { name: 'description', label: 'Description', widget: 'string' }
         - { name: 'url', label: 'URL', widget: 'string'}
         - { name: 'logo', label: 'Logo', widget: 'image'}
         - { name: 'paginate', label: 'Pagination', widget: 'number'}
         - name: 'navigation_header'
           label: 'Navigation Header' 
           widget: 'list'
           fields:
           - { name: 'title', label: 'Title', widget: 'string' }
           - { name: 'url', label: 'URL Link', widget: 'string' }
         - name: 'navigation_footer'
           label: 'Navigation Footer' 
           widget: 'list'
           fields:
           - { name: 'title', label: 'Title', widget: 'string' }
           - { name: 'url', label: 'URL Link', widget: 'string' }